variables:
  CIMPL_SERVICE: partition
  CIMPL_ENABLE_BOOTSTRAP: "true"
  CIMPL_BUILD_BOOTSTRAP_PATH: "devops/core-plus/bootstrap/Dockerfile"
  DISABLE_INTEGRATION_TEST: true

cimpl-acceptance-test:
  variables:
    PARTITION_BASE_URL: https://osdu.dev1.osdu-cimpl.opengroup.org/
    MY_TENANT: "osdu"

#Dev2 Jobs

cimpl-dev2-acceptance-test:
  variables:
    PARTITION_BASE_URL: https://osdu.dev2.osdu-cimpl.opengroup.org/
    MY_TENANT: "osdu"