#
# Copyright 2020-2025 Google LLC
# Copyright 2020-2025 EPAM Systems, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#server config
server.servlet.contextPath=/api/partition/v1
server.port=8080
springfox.documentation.swagger.v2.path=/api-docs
management.endpoint.health.show-details=always
management.health.diskspace.enabled=false
ACCEPT_HTTP=true

#logging configuration
logging.level.org.springframework.web=${LOG_LEVEL:INFO}
LOG_PREFIX=partition

#cache config
cache-expiration=1
cache-maxSize=1000

#service config
destination.resolver=property
partition-property-kind=PartitionProperty
partition-namespace=partition
dataPartitionId = ${DATA_PARTITION_ID:test-partition}
environment=gcp
google-cloud-project=${GOOGLE_CLOUD_PROJECT}

#System Tenant
system-partition-id=system

# Health checks
management.server.port=${MANAGEMENT_SERVER_PORT:8081}
management.endpoints.web.base-path=${MANAGEMENT_ENDPOINTS_WEB_BASE:/}
management.endpoints.web.exposure.include=health
management.health.probes.enabled=true
